#spring:
#  application:
#    name: SpringCrudDemoApplication
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/student
#    username: root
#    password: ammu
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      database-platform: org.hibernate.dialect.MySQLDialect
#      ddl-auto: update
#
#
#server:
#  port: 9191